name: OSX

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate
      run: cmake . -B.build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build .build/

    - name: Test
      run: |
        cd .build/
        ctest .